### ISSUE TITLE
None to Decimal error

### ISSUE THREAD

**Issue by oceanlazy** [exante/python-http-broker-example#1]
```
(venv) v@ubuntu:~/PycharmProjects/python-http-broker-example/http-broker-example$ python http-broker-example.py ebea292f-c8a4-4da4-8ce5-72ecc6c8b34b XWC8279.001 --token RWfBuLKnd3aeYxrYM9mG
Traceback (most recent call last):
  File "http-broker-example.py", line 61, in <module>
    worker.run(args.instrument, args.quantity, args.grid)
  File "/home/v/PycharmProjects/python-http-broker-example/http-broker-example/libs/grid_broker_worker.py", line 114, in run
    mid = (self.dec(quote['bid']) + self.dec(quote['ask'])) / 2
  File "/home/v/PycharmProjects/python-http-broker-example/http-broker-example/libs/grid_broker_worker.py", line 62, in dec
    return decimal.Decimal(str(value))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by oceanlazy** [comment]
I think the error was due to the fact that the EUR/USD.E.FX did not bargain at the time when I ran it, but it would be nice to add information about this in the readme.

**Comment by vden** [comment]
Thank you for the issue. You're right, quote feed might be unavailable when market is on schedule break.

We'll update endpoint description accordingly.
